# Generated by Django 3.1.5 on 2021-02-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0002_auto_20210216_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='profile',
        ),
    ]
