# Generated by Django 3.1.5 on 2021-02-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0003_auto_20210217_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
