# Generated by Django 3.1.5 on 2021-02-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0006_auto_20210223_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Applied'), ('O', 'Offered'), ('R', 'Rejected')], max_length=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applicant', to='LFGCore.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_role', to='LFGCore.role')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='application',
            field=models.ManyToManyField(through='LFGCore.Application', to='LFGCore.Role'),
        ),
    ]
