# Generated by Django 3.1.5 on 2021-02-25 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0007_auto_20210224_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application',
        ),
        migrations.AddField(
            model_name='profile',
            name='applications',
            field=models.ManyToManyField(related_name='role_application', through='LFGCore.Application', to='LFGCore.Role'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LFGCore.profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LFGCore.role'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('O', 'Offered'), ('C', 'Accepted'), ('R', 'Rejected')], max_length=1),
        ),
    ]
