# Generated by Django 3.1.5 on 2021-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0008_auto_20210225_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('O', 'Offered'), ('R', 'Rejected'), ('D', 'Declined')], max_length=1),
        ),
    ]
