# Generated by Django 3.1.5 on 2021-03-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0009_auto_20210226_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(related_name='memberships', through='LFGCore.Member', to='LFGCore.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
