# Generated by Django 3.1.5 on 2021-04-07 22:44

import LFGCore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LFGCore', '0010_auto_20210301_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=LFGCore.models.now),
        ),
    ]
